name: Hello Workflow

on: push

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello from GitHub Actions!"
      - run: echo "Step 1"
      - run: echo "Step 2"
      - run: date
